
services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ee
    container_name: ${APPSMITH_CONTAINER_NAME:-appsmith}
    hostname: ${APPSMITH_HOSTNAME:-appsmith}
    ports:
      - "${APPSMITH_PORT:-8080}:80"
      - "${APPSMITH_PORT:-8443}:443"
    restart: unless-stopped
    #environment:
      #APPSMITH_DB_URL: mongodb+srv: {username}:{password}@{mongo.host.name}/{db_name}
      #APPSMITH_REDIS_URL=redis: {redis.instance.hostname}:{port}
      #APPSMITH_KEYCLOAK_DB_URL: postgresql://appsmith:password@appsmith.postgres.database.azure.com:5432/keycloak
      #APPSMITH_GOOGLE_MAPS_API_KEY: YOUR_API_KEY
    volumes:
      - appsmith-stacks:/appsmith-stacks
    networks:
      - portainer-network

volumes:
  appsmith-stacks: {}

networks:
  portainer-network:
    external: true
