
services:
  neo4j:
    image: neo4j:${NEO4J_TAG:-latest}
    container_name: ${NEO4J_CONTAINER_NAME:-neo4j}
    hostname: ${NEO4J_HOSTNAME:-neo4j}
    ports:
      - "${NEO4J_BOLT_PORT:-7687}:7687"
      - "${NEO4J_HTTP_PORT:-7474}:7474"
    restart: unless-stopped
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH:-neo4j/password}
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
    networks:
      - portainer-network

volumes:
  neo4j-data: {}
  neo4j-logs: {}
  neo4j-import: {}
  neo4j-plugins: {}

networks:
  portainer-network:
    external: true
