
services:
  postgres:
    image: postgres:${POSTGRES_TAG:-latest}
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
    hostname: ${POSTGRES_HOSTNAME:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - portainer-network

volumes:
  postgres-data: {}

networks:
  portainer-network:
    external: true
