
services:
  mongodb:
    image: mongo:${MONGO_TAG:-latest}
    container_name: ${MONGO_CONTAINER_NAME:-mongodb}
    hostname: ${MONGO_HOSTNAME:-mongodb}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-root}
    volumes:
      - mongodb-data:/data/db
    networks:
      - portainer-network

volumes:
  mongodb-data: {}

networks:
  portainer-network:
    external: true
